name: kostrykin.com
owner: Dr. Leonid Kostrykin

collections:
  publications:
    output: true
    permalink: /:collection/:title.bib

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: bibtex
