name: kostrykin.com
owner: Dr. Leonid Kostrykin

collections:
  publications:
    output: true
    permalink: /:collection/:title.bib
  notes:
    output: true
    permalink: /:collection/notes/:title

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  - scope:
      path: ""
      type: notes
    values:
      layout: notes
