name: kostrykin.com
owner: Dr. Leonid Kostrykin

collections:
  publications:
    output: true
    permalink: /:collection/:title.bib
  notes:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      type: publications
      path: ""
    values:
      layout: publication
  - scope:
      type: notes
      path: ""
    values:
      layout: notes
      title: Publication Notes      
      nav_publications: active

exclude:
  - .env
